/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/emergency_details.dart';
import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:asn1_plugin/j2735/2024/common/minute_of_the_year.dart';
import 'package:asn1_plugin/j2735/2024/common/response_type.dart';
import 'package:asn1_plugin/j2735/2024/common/temporary_id.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_mass.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_type.dart';
import 'package:asn1_plugin/j2735/2024/itis/incident_response_equipment.dart';
import 'package:asn1_plugin/j2735/2024/itis/responder_group_affected.dart';
import 'package:asn1_plugin/j2735/2024/itis/vehicle_group_affected.dart';
import 'package:asn1_plugin/j2735/2024/road_side_alert/road_side_alert.dart';

class EmergencyVehicleAlert {
  MinuteOfTheYear? timeStamp = null;
  TemporaryID? id = null;
  late RoadSideAlert rsaMsg;
  ResponseType? responseType = null;
  EmergencyDetails? details = null;
  VehicleMass? mass = null;
  VehicleType? basicType = null;
  VehicleGroupAffected? vehicleType = null;
  IncidentResponseEquipment? responseEquip = null;
  ResponderGroupAffected? responderType = null;

  EmergencyVehicleAlert(this.rsaMsg) {}

  EmergencyVehicleAlert.fromC(C.EmergencyVehicleAlert c_obj) {
    if (c_obj.timeStamp.address != 0) {
      timeStamp = MinuteOfTheYear(c_obj.timeStamp.value);
    }

    if (c_obj.id.address != 0) {
      id = TemporaryID.fromOctetString(c_obj.id.ref);
    }

    rsaMsg = RoadSideAlert.fromC(c_obj.rsaMsg);
    if (c_obj.responseType.address != 0) {
      responseType = ResponseType.values[c_obj.responseType.value];
    }

    if (c_obj.details.address != 0) {
      details = EmergencyDetails.fromC(c_obj.details.ref);
    }

    if (c_obj.mass.address != 0) {
      mass = VehicleMass(c_obj.mass.value);
    }

    if (c_obj.basicType.address != 0) {
      basicType = VehicleType.values[c_obj.basicType.value];
    }

    if (c_obj.vehicleType.address != 0) {
      vehicleType = VehicleGroupAffected.values[c_obj.vehicleType.value];
    }

    if (c_obj.responseEquip.address != 0) {
      responseEquip = IncidentResponseEquipment.values[c_obj.responseEquip.value];
    }

    if (c_obj.responderType.address != 0) {
      responderType = ResponderGroupAffected.values[c_obj.responderType.value];
    }
  }

  Pointer<C.EmergencyVehicleAlert> toC() {
    Pointer<C.EmergencyVehicleAlert> alert = calloc<C.EmergencyVehicleAlert>();

    if (timeStamp != null) {
      Pointer<Long> value = calloc<Long>();
      value.value = timeStamp!.minuteOfTheYear;
      alert.ref.timeStamp = value;
    }

    return alert;
  }
}
