/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/extent.dart';
import 'package:asn1_plugin/j2735/2024/common/full_position_vector.dart';
import 'package:asn1_plugin/j2735/2024/common/heading_slice.dart';
import 'package:asn1_plugin/j2735/2024/common/minute_of_the_year.dart';
import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'package:asn1_plugin/j2735/2024/common/priority.dart';
import 'package:asn1_plugin/j2735/2024/common/further_info_id.dart';
import 'package:asn1_plugin/j2735/2024/itis/itis_codes.dart';

class RoadSideAlert {
  late MsgCount msgCnt;
  MinuteOfTheYear? timeStamp = null;
  late ITIScodes typeEvent;
  List<ITIScodes>? description = null;
  Priority? priority = null;
  HeadingSlice? heading = null;
  Extent? extent = null;
  FullPositionVector? position = null;
  FurtherInfoId? furtherInfoID = null;

  RoadSideAlert.fromC(C.RoadSideAlert c_obj) {
    msgCnt = MsgCount(c_obj.msgCnt);
    if (c_obj.timeStamp.address != 0) {
      timeStamp = MinuteOfTheYear(c_obj.timeStamp.value);
    }

    typeEvent = ITIScodes(c_obj.typeEvent);
    if (c_obj.description.address != 0) {
      description = [];
      for (int i = 0; i < c_obj.description.ref.list.count; i++) {
        description!.add(ITIScodes(c_obj.description.ref.list.array[i].value));
      }
    }

    if (c_obj.priority.address != 0) {
      priority = Priority(c_obj.priority.ref);
    }

    if (c_obj.heading.address != 0) {
      heading = HeadingSlice.fromBitString(c_obj.heading.ref);
    }

    if (c_obj.extent.address != 0) {
      extent = Extent.values[c_obj.extent.value];
    }

    if (c_obj.position.address != 0) {
      position = FullPositionVector.fromC(c_obj.position.ref);
    }

    if (c_obj.furtherInfoID.address != 0) {
      furtherInfoID = FurtherInfoId.fromOctetString(c_obj.furtherInfoID.ref);
    }
  }
}
