/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'package:asn1_plugin/j2735/2024/common/temporary_id.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_charger_info.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/encrypted_tum_data.dart';
import 'package:asn1_plugin/j3217/2022/toll_usage_message/tum_hash.dart';

import 'package:ffi/ffi.dart';


class TollUsageMessage{
    late TollChargerInfo tollPointInfo; 
    late TemporaryID tempID; 
    late MsgCount tumSequenceNum; 
    late MsgCount tamSequenceNum; 
    TumHash? tumHash; 
    late EncryptedTumData encryptedTumData; 
    TollUsageMessage.fromC(C.TollUsageMessage c_obj){
        tollPointInfo = TollChargerInfo.fromC(c_obj.tollPointInfo);
        tempID = TemporaryID.fromOctetString(c_obj.tempID);
        tumSequenceNum = MsgCount(c_obj.tumSequenceNum);
        tamSequenceNum = MsgCount(c_obj.tamSequenceNum);
        if(c_obj.tumHash.address != 0){
            tumHash = TumHash.fromOctetString(c_obj.tumHash.ref);
        }
        encryptedTumData = EncryptedTumData.fromOctetString(c_obj.encryptedTumData);
    }

    C.TollUsageMessage toC(Pointer<C.TollUsageMessage> pointer) {
      print("Big Gorilla 1.1");
      final c_tum = pointer.ref;
      print("Big Gorilla 1.2");
      c_tum.tollPointInfo = tollPointInfo.toC(calloc.allocate<C.TollChargerInfo>(sizeOf<C.TollChargerInfo>()));
      print("Big Gorilla 1.3");
      c_tum.tempID = tempID.toC(calloc.allocate<C.OCTET_STRING>(sizeOf<C.OCTET_STRING>()));
      print("Big Gorilla 1.4");
      c_tum.tumSequenceNum = 0;
      print("Big Gorilla 1.5");
      c_tum.tamSequenceNum = 0;
      print("Big Gorilla 1.6");
      if(tumHash != null){
        //Cookie - ToDo
      }
      print("Big Gorilla 1.7");
      c_tum.encryptedTumData = encryptedTumData.toC(calloc.allocate<C.OCTET_STRING>(sizeOf<C.OCTET_STRING>()));
      print("Big Gorilla 1.8");
      return c_tum;
    }

    //pass in memory that I want it to allocate
    //ToC method
    //pass in a pointer to the c.tum as well
    //might need to return a list of all memory pointers
    //look to generated bindings - send through ai to get c memory allocation

}
