/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'dart:convert';
import 'dart:typed_data';

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';


class TumHash{
  String? tumHash;

  TumHash.fromOctetString(C.OCTET_STRING string){
    final Uint8List byteList = string.buf.asTypedList(string.size);
    //tumHash = utf8.decode(byteList);
    //Cookie
    tumHash = byteList.map((b) => b.toRadixString(16).padLeft(2, '0')).join('');
  }

  C.OCTET_STRING toC(Pointer<C.OCTET_STRING> pointer) {
    final c_tumHash = pointer.ref;
    final bytes = <int>[];
    for (int i = 0; i < tumHash!.length; i += 2) {
      bytes.add(int.parse(tumHash!.substring(i, i + 2), radix: 16));
    }
    for (int i = 0; i < bytes.length; i++) {
      c_tumHash.buf[i] = bytes[i];
    }
    c_tumHash.size = bytes.length;
    return c_tumHash;
  }
}