/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/pitch_rate_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/roll_rate_confidence.dart';

class AngularVelocityConfidence {
  PitchRateConfidence? pitchRateConfidence = null;
  RollRateConfidence? rollRateConfidence = null;
  AngularVelocityConfidence.fromC(C.AngularVelocityConfidence c_obj) {
    if (c_obj.pitchRateConfidence.address != 0) {
      pitchRateConfidence = PitchRateConfidence.values[c_obj.pitchRateConfidence.value];
    }

    if (c_obj.rollRateConfidence.address != 0) {
      rollRateConfidence = RollRateConfidence.values[c_obj.rollRateConfidence.value];
    }
  }
}
