/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/probe_vehicle_data/acceleration_confidence.dart';
import 'package:asn1_plugin/j2735/2024/probe_vehicle_data/yaw_rate_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/object_type.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/position_offset_xyz.dart';
import 'package:asn1_plugin/j2735/2024/common/acceleration_set_4_way.dart';
import 'package:asn1_plugin/j2735/2024/common/heading.dart';
import 'package:asn1_plugin/j2735/2024/common/heading_confidence.dart';
import 'package:asn1_plugin/j2735/2024/common/position_confidence_set.dart';
import 'package:asn1_plugin/j2735/2024/common/speed.dart';
import 'package:asn1_plugin/j2735/2024/common/speed_confidence.dart';
import 'package:asn1_plugin/j2735/2024/common/time_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/classification_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/measurement_time_offset.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/object_id.dart';

class DetectedObjectCommonData {
  late ObjectType objType;
  late ClassificationConfidence objTypeCfd;
  late ObjectID objectID;
  late MeasurementTimeOffset measurementTime;
  late TimeConfidence timeConfidence;
  late PositionOffsetXYZ pos;
  late PositionConfidenceSet posConfidence;
  late Speed speed;
  late SpeedConfidence speedConfidence;
  Speed? speedZ = null;
  SpeedConfidence? speedConfidenceZ = null;
  late Heading heading;
  late HeadingConfidence headingConf;
  AccelerationSet4Way? accel4way = null;
  AccelerationConfidence? accCfdX = null;
  AccelerationConfidence? accCfdY = null;
  AccelerationConfidence? accCfdZ = null;
  YawRateConfidence? accCfdYaw = null;
  DetectedObjectCommonData.fromC(C.DetectedObjectCommonData c_obj) {
    objType = ObjectType.values[c_obj.objType];
    objTypeCfd = ClassificationConfidence(c_obj.objTypeCfd);
    objectID = ObjectID(c_obj.objectID);
    measurementTime = MeasurementTimeOffset(c_obj.measurementTime);
    timeConfidence = TimeConfidence.values[c_obj.timeConfidence];
    pos = PositionOffsetXYZ.fromC(c_obj.pos);
    posConfidence = PositionConfidenceSet.fromC(c_obj.posConfidence);
    speed = Speed(c_obj.speed);
    speedConfidence = SpeedConfidence.values[c_obj.speedConfidence];
    if (c_obj.speedZ.address != 0) {
      speedZ = Speed(c_obj.speedZ.value);
    }

    if (c_obj.speedConfidenceZ.address != 0) {
      speedConfidenceZ = SpeedConfidence.values[c_obj.speedConfidenceZ.value];
    }

    heading = Heading(c_obj.heading);
    headingConf = HeadingConfidence.values[c_obj.headingConf];
    if (c_obj.accel4way.address != 0) {
      accel4way = AccelerationSet4Way.fromC(c_obj.accel4way.ref);
    }

    if (c_obj.accCfdX.address != 0) {
      accCfdX = AccelerationConfidence.values[c_obj.accCfdX.value];
    }

    if (c_obj.accCfdY.address != 0) {
      accCfdY = AccelerationConfidence.values[c_obj.accCfdY.value];
    }

    if (c_obj.accCfdZ.address != 0) {
      accCfdZ = AccelerationConfidence.values[c_obj.accCfdZ.value];
    }

    if (c_obj.accCfdYaw.address != 0) {
      accCfdYaw = YawRateConfidence.values[c_obj.accCfdYaw.value];
    }
  }
}
