/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/basic_vehicle_class.dart';
import 'package:asn1_plugin/j2735/2024/common/exterior_lights.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_height.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_size.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/angular_velocity.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/angular_velocity_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/attitude.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/attitude_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/classification_confidence.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/vehicle_size_confidence.dart';

class DetectedVehicleData {
  ExteriorLights? lights = null;
  Attitude? vehAttitude = null;
  AttitudeConfidence? vehAttitudeConfidence = null;
  AngularVelocity? vehAngVel = null;
  AngularVelocityConfidence? vehAngVelConfidence = null;
  VehicleSize? size = null;
  VehicleHeight? height = null;
  VehicleSizeConfidence? vehicleSizeConfidence = null;
  BasicVehicleClass? vehicleClass = null;
  ClassificationConfidence? classConf = null;
  DetectedVehicleData.fromC(C.DetectedVehicleData c_obj) {
    if (c_obj.lights.address != 0) {
      lights = ExteriorLights.fromBitString(c_obj.lights.ref);
    }

    if (c_obj.vehAttitude.address != 0) {
      vehAttitude = Attitude.fromC(c_obj.vehAttitude.ref);
    }

    if (c_obj.vehAttitudeConfidence.address != 0) {
      vehAttitudeConfidence = AttitudeConfidence.fromC(c_obj.vehAttitudeConfidence.ref);
    }

    if (c_obj.vehAngVel.address != 0) {
      vehAngVel = AngularVelocity.fromC(c_obj.vehAngVel.ref);
    }

    if (c_obj.vehAngVelConfidence.address != 0) {
      vehAngVelConfidence = AngularVelocityConfidence.fromC(c_obj.vehAngVelConfidence.ref);
    }

    if (c_obj.size.address != 0) {
      size = VehicleSize.fromC(c_obj.size.ref);
    }

    if (c_obj.height.address != 0) {
      height = VehicleHeight(c_obj.height.value);
    }

    if (c_obj.vehicleSizeConfidence.address != 0) {
      vehicleSizeConfidence = VehicleSizeConfidence.fromC(c_obj.vehicleSizeConfidence.ref);
    }

    if (c_obj.vehicleClass.address != 0) {
      vehicleClass = BasicVehicleClass(c_obj.vehicleClass.value);
    }

    if (c_obj.classConf.address != 0) {
      classConf = ClassificationConfidence(c_obj.classConf.value);
    }
  }
}
