/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/personal_safety_message/attachment.dart';
import 'package:asn1_plugin/j2735/2024/personal_safety_message/attachment_radius.dart';
import 'package:asn1_plugin/j2735/2024/personal_safety_message/personal_device_user_type.dart';
import 'package:asn1_plugin/j2735/2024/personal_safety_message/propelled_information.dart';

class DetectedVRUData {
  PersonalDeviceUserType? basicType = null;
  PropelledInformation? propulsion = null;
  Attachment? attachment = null;
  AttachmentRadius? radius = null;
  DetectedVRUData.fromC(C.DetectedVRUData c_obj) {
    if (c_obj.basicType.address != 0) {
      basicType = PersonalDeviceUserType.values[c_obj.basicType.value];
    }

    if (c_obj.propulsion.address != 0) {
      propulsion = PropelledInformation.fromC(c_obj.propulsion.ref);
    }

    if (c_obj.attachment.address != 0) {
      attachment = Attachment.values[c_obj.attachment.value];
    }

    if (c_obj.radius.address != 0) {
      radius = AttachmentRadius(c_obj.radius.value);
    }
  }
}
