/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/detected_object_common_data.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/detected_object_optional_data.dart';

class DetectedObjectData {
  late DetectedObjectCommonData detObjCommon;
  DetectedObjectOptionalData? detObjOptData = null;
  DetectedObjectData.fromC(C.DetectedObjectData c_obj) {
    detObjCommon = DetectedObjectCommonData.fromC(c_obj.detObjCommon);
    if (c_obj.detObjOptData.address != 0) {
      detObjOptData = DetectedObjectOptionalData.fromC(c_obj.detObjOptData.ref);
    }
  }
}
