/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j2735/2024/common/elevation_confidence.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'package:asn1_plugin/j2735/2024/common/position_3d.dart';
import 'package:asn1_plugin/j2735/2024/common/positional_accuracy.dart';
import 'package:asn1_plugin/j2735/2024/common/temporary_id.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/detected_object_list.dart';
import 'package:asn1_plugin/j2735/2024/sensor_data_sharing_message/equipment_type.dart';

class SensorDataSharingMessage {
  late MsgCount msgCnt;
  late TemporaryID sourceID;
  late EquipmentType equipmentType;
  late DDateTime sDSMTimeStamp;
  late Position3D refPos;
  late PositionalAccuracy refPosXYConf;
  ElevationConfidence? refPosElConf = null;
  late DetectedObjectList objects;
  SensorDataSharingMessage.fromC(C.SensorDataSharingMessage c_obj) {
    msgCnt = MsgCount(c_obj.msgCnt);
    sourceID = TemporaryID.fromOctetString(c_obj.sourceID);
    equipmentType = EquipmentType.values[c_obj.equipmentType];
    sDSMTimeStamp = DDateTime.fromC(c_obj.sDSMTimeStamp);
    refPos = Position3D.fromC(c_obj.refPos);
    refPosXYConf = PositionalAccuracy.fromC(c_obj.refPosXYConf);
    if (c_obj.refPosElConf.address != 0) {
      refPosElConf = ElevationConfidence.values[c_obj.refPosElConf.value];
    }

    objects = DetectedObjectList.fromC(c_obj.objects);
  }
}
