/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/basic_vehicle_role.dart';
import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'package:asn1_plugin/j2735/2024/common/request_id.dart';
import 'package:asn1_plugin/j2735/2024/common/requestor_type.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_id.dart';

class SignalRequesterInfo {
  late VehicleID id;
  late RequestID request;
  late MsgCount sequenceNumber;
  BasicVehicleRole? role = null;
  RequestorType? typeData = null;
  SignalRequesterInfo.fromC(C.SignalRequesterInfo c_obj) {
    id = VehicleID.fromC(c_obj.id);
    request = RequestID(c_obj.request);
    sequenceNumber = MsgCount(c_obj.sequenceNumber);
    if (c_obj.role.address != 0) {
      role = BasicVehicleRole.values[c_obj.role.value];
    }

    if (c_obj.typeData.address != 0) {
      typeData = RequestorType.fromC(c_obj.typeData.ref);
    }
  }
}
