/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/d_second.dart';
import 'package:asn1_plugin/j2735/2024/common/minute_of_the_year.dart';
import 'package:asn1_plugin/j2735/2024/common/msg_count.dart';
import 'package:asn1_plugin/j2735/2024/signal_status_message/signal_status_list.dart';

class SignalStatusMessage {
  MinuteOfTheYear? timeStamp = null;
  late DSecond second;
  MsgCount? sequenceNumber = null;
  late SignalStatusList status;
  SignalStatusMessage.fromC(C.SignalStatusMessage c_obj) {
    if (c_obj.timeStamp.address != 0) {
      timeStamp = MinuteOfTheYear(c_obj.timeStamp.value);
    }

    second = DSecond(c_obj.second);
    if (c_obj.sequenceNumber.address != 0) {
      sequenceNumber = MsgCount(c_obj.sequenceNumber.value);
    }

    status = SignalStatusList.fromC(c_obj.status);
  }
}
