/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/d_second.dart';
import 'package:asn1_plugin/j2735/2024/common/minute_of_the_year.dart';
import 'package:asn1_plugin/j2735/2024/common/prioritization_response_status.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/intersection_access_point.dart';
import 'package:asn1_plugin/j2735/2024/signal_status_message/signal_requester_info.dart';
import 'dart:ffi';

class SignalStatusPackage {
  SignalRequesterInfo? requester = null;
  late IntersectionAccessPoint inboundOn;
  IntersectionAccessPoint? outboundOn = null;
  MinuteOfTheYear? minute = null;
  DSecond? second = null;
  DSecond? duration = null;
  late PrioritizationResponseStatus status;

  SignalStatusPackage.fromC(C.SignalStatusPackage c_obj) {
    if (c_obj.requester.address != 0) {
      requester = SignalRequesterInfo.fromC(c_obj.requester.ref);
    }

    inboundOn = IntersectionAccessPoint.fromC(c_obj.inboundOn);
    if (c_obj.outboundOn.address != 0) {
      outboundOn = IntersectionAccessPoint.fromC(c_obj.outboundOn.ref);
    }

    if (c_obj.minute.address != 0) {
      minute = MinuteOfTheYear(c_obj.minute.value);
    }

    if (c_obj.second.address != 0) {
      second = DSecond(c_obj.second.value);
    }

    if (c_obj.duration.address != 0) {
      duration = DSecond(c_obj.duration.value);
    }

    status = PrioritizationResponseStatus.values[c_obj.status];
  }
}
