/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

enum GenericLocations {
  on_bridges,
  in_tunnels,
  entering_or_leaving_tunnels,
  on_ramps,
  in_road_construction_area,
  around_a_curve,
  on_curve,
  on_tracks,
  in_street,
  shoulder,
  on_minor_roads,
  in_the_opposing_lanes,
  adjacent_to_roadway,
  across_tracks,
  on_bend,
  intersection,
  entire_intersection,
  in_the_median,
  moved_to_side_of_road,
  moved_to_shoulder,
  on_the_roadway,
  dip,
  traffic_circle,
  crossover,
  cross_road,
  side_road,
  to_,
  by,
  through,
  area_of,
  under,
  over,
  from,
  approaching,
  entering_at,
  exiting_at,
  in_shaded_areas,
  in_low_lying_areas,
  in_the_downtown_area,
  in_the_inner_city_area,
  in_parts,
  in_some_places,
  in_the_ditch,
  in_the_valley,
  on_hill_top,
  near_the_foothills,
  at_high_altitudes,
  near_the_lake,
  near_the_shore,
  nearby_basin,
  over_the_crest_of_a_hill,
  other_than_on_the_roadway,
  near_the_beach,
  near_beach_access_point,
  mountain_pass,
  lower_level,
  upper_level,
  airport,
  concourse,
  gate,
  baggage_claim,
  customs_point,
  reservation_center,
  station,
  platform,
  dock,
  depot,
  ev_charging_point,
  information_welcome_point,
  at_rest_area,
  at_service_area,
  at_weigh_station,
  roadside_park,
  picnic_areas,
  rest_area,
  service_stations,
  toilets,
  bus_stop,
  park_and_ride_lot,
  on_the_right,
  on_the_left,
  in_the_center,
  in_the_opposite_direction,
  cross_traffic,
  northbound_traffic,
  eastbound_traffic,
  southbound_traffic,
  westbound_traffic,
  north,
  south,
  east,
  west,
  northeast,
  northwest,
  southeast,
  southwest,
}
