/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

enum IncidentResponseEquipment{
    ground_fire_suppression,
    heavy_ground_equipment,
    aircraft,
    marine_equipment,
    support_equipment,
    medical_rescue_unit,
    other,
    ground_fire_suppression_other,
    engine,
    truck_or_aerial,
    quint,
    tanker_pumper_combination,
    brush_truck,
    aircraft_rescue_firefighting,
    heavy_ground_equipment_other,
    dozer_or_plow,
    tractor,
    tanker_or_tender,
    aircraft_other,
    aircraft_fixed_wing_tanker,
    helitanker,
    helicopter,
    marine_equipment_other,
    fire_boat_with_pump,
    boat_no_pump,
    support_apparatus_other,
    breathing_apparatus_support,
    light_and_air_unit,
    medical_rescue_unit_other,
    rescue_unit,
    urban_search_rescue_unit,
    high_angle_rescue,
    crash_fire_rescue,
    bLS_unit,
    aLS_unit,
    mobile_command_post,
    chief_officer_car,
    hAZMAT_unit,
    type_i_hand_crew,
    type_ii_hand_crew,
    privately_owned_vehicle,
    other_apparatus_resource,
    ambulance,
    bomb_squad_van,
    combine_harvester,
    construction_vehicle,
    farm_tractor,
    grass_cutting_machines,
    hAZMAT_containment_tow,
    heavy_tow,
    light_tow,
    flatbed_tow,
    hedge_cutting_machines,
    mobile_crane,
    refuse_collection_vehicle,
    resurfacing_vehicle,
    road_sweeper,
    roadside_litter_collection_crews,
    salvage_vehicle,
    sand_truck,
    snowplow,
    steam_roller,
    swat_team_van,
    track_laying_vehicle,
    unknown_vehicle,
    white_lining_vehicle,
    dump_truck,
    supervisor_vehicle,
    snow_blower,
    rotary_snow_blower,
    road_grader,
    steam_truck,
}