/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

enum VehicleGroupAffected{
    all_vehicles,
    bicycles,
    motorcycles,
    cars,
    light_vehicles,
    cars_and_light_vehicles,
    cars_with_trailers,
    cars_with_recreational_trailers,
    vehicles_with_trailers,
    heavy_vehicles,
    trucks,
    buses,
    articulated_buses,
    school_buses,
    vehicles_with_semi_trailers,
    vehicles_with_double_trailers,
    high_profile_vehicles,
    wide_vehicles,
    long_vehicles,
    hazardous_loads,
    exceptional_loads,
    abnormal_loads,
    convoys,
    maintenance_vehicles,
    delivery_vehicles,
    vehicles_with_even_numbered_license_plates,
    vehicles_with_odd_numbered_license_plates,
    vehicles_with_parking_permits,
    vehicles_with_catalytic_converters,
    vehicles_without_catalytic_converters,
    gas_powered_vehicles,
    diesel_powered_vehicles,
    lPG_vehicles,
    military_convoys,
    military_vehicles,
}