/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

class Axles {
  late TotalAxlesInteger totalAxles;
  FrontAxlesInteger? frontAxles = null;
  RearAxlesInteger? rearAxles = null;
  Axles.fromC(C.Axles c_obj) {
    totalAxles = TotalAxlesInteger(c_obj.totalAxles);
    if (c_obj.frontAxles.address != 0) {
      frontAxles = FrontAxlesInteger(c_obj.frontAxles.value);
    }

    if (c_obj.rearAxles.address != 0) {
      rearAxles = RearAxlesInteger(c_obj.rearAxles.value);
    }
  }
}

class TotalAxlesInteger {
  late int totalAxlesInteger;
  TotalAxlesInteger(int totalAxlesInteger);
}

class FrontAxlesInteger {
  late int frontAxlesInteger;
  FrontAxlesInteger(int frontAxlesInteger);
}

class RearAxlesInteger {
  late int rearAxlesInteger;
  RearAxlesInteger(int rearAxlesInteger);
}
