/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/portland_cement.dart';
import 'package:asn1_plugin/j2735/2024/common/asphalt_or_tar.dart';
import 'package:asn1_plugin/j2735/2024/common/gravel.dart';
import 'package:asn1_plugin/j2735/2024/common/grass.dart';
import 'package:asn1_plugin/j2735/2024/common/cinders.dart';
import 'package:asn1_plugin/j2735/2024/common/rock.dart';
import 'package:asn1_plugin/j2735/2024/common/ice.dart';
import 'package:asn1_plugin/j2735/2024/common/snow.dart';

class DescriptionOfRoadSurface {
  late PortlandCement portlandCement;
  late AsphaltOrTar asphaltOrTar;
  late Gravel gravel;
  late Grass grass;
  late Cinders cinders;
  late Rock rock;
  late Ice ice;
  late Snow snow;
  DescriptionOfRoadSurface.fromC(C.DescriptionOfRoadSurface c_obj) {
    portlandCement = PortlandCement.fromC(c_obj.choice.portlandCement);
    asphaltOrTar = AsphaltOrTar.fromC(c_obj.choice.asphaltOrTar);
    gravel = Gravel.fromC(c_obj.choice.gravel);
    grass = Grass.fromC(c_obj.choice.grass);
    cinders = Cinders.fromC(c_obj.choice.cinders);
    rock = Rock.fromC(c_obj.choice.rock);
    ice = Ice.fromC(c_obj.choice.ice);
    snow = Snow.fromC(c_obj.choice.snow);
  }
}
