/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/common/lightbar_in_use.dart';
import 'package:asn1_plugin/j2735/2024/common/multi_vehicle_response.dart';
import 'package:asn1_plugin/j2735/2024/common/privileged_events.dart';
import 'package:asn1_plugin/j2735/2024/common/response_type.dart';
import 'package:asn1_plugin/j2735/2024/common/siren_in_use.dart';
import 'package:asn1_plugin/j2735/2024/common/sspindex.dart';
import 'dart:ffi';

class EmergencyDetails {
  late SSPindex doNotUse;
  late SirenInUse sirenUse;
  late LightbarInUse lightsUse;
  late MultiVehicleResponse multi;
  PrivilegedEvents? events = null;
  ResponseType? responseType = null;
  EmergencyDetails.fromC(C.EmergencyDetails c_obj) {
    doNotUse = SSPindex(c_obj.doNotUse);
    sirenUse = SirenInUse.values[c_obj.sirenUse];
    lightsUse = LightbarInUse.values[c_obj.lightsUse];
    multi = MultiVehicleResponse.values[c_obj.multi];
    if (c_obj.events.address != 0) {
      events = PrivilegedEvents.fromC(c_obj.events.ref);
    }

    if (c_obj.responseType.address != 0) {
      responseType = ResponseType.values[c_obj.responseType.value];
    }
  }
}
