/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

class ExteriorLights {
  late bool lowBeamHeadlightsOn;
  late bool highBeamHeadlightsOn;
  late bool leftTurnSignalOn;
  late bool rightTurnSignalOn;
  late bool hazardSignalOn;
  late bool automaticLightControlOn;
  late bool daytimeRunningLightsOn;
  late bool fogLightsOn;
  late bool parkingLightsOn;

  ExteriorLights.fromBitString(C.BIT_STRING_s bits) {
    List<int> decodedBits = bits.buf.asTypedList(bits.size);

    lowBeamHeadlightsOn = (decodedBits[0] & (1 << 7)) != 0;
    highBeamHeadlightsOn = (decodedBits[0] & (1 << 6)) != 0;
    leftTurnSignalOn = (decodedBits[0] & (1 << 5)) != 0;
    rightTurnSignalOn = (decodedBits[0] & (1 << 4)) != 0;
    hazardSignalOn = (decodedBits[0] & (1 << 3)) != 0;
    automaticLightControlOn = (decodedBits[0] & (1 << 2)) != 0;
    daytimeRunningLightsOn = (decodedBits[0] & (1 << 1)) != 0;
    fogLightsOn = (decodedBits[0] & (1 << 0)) != 0;
    parkingLightsOn = (decodedBits[1] & (1 << 7)) != 0;
  }
}
