/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/obstacle_distance.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/obstacle_direction.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/itiscodes.dart';
import 'package:asn1_plugin/j2735/2024/itis/generic_locations.dart';
import 'package:asn1_plugin/j2735/2024/common/d_date_time.dart';
import 'package:asn1_plugin/j2735/2024/common/vertical_acceleration_threshold.dart';

class ObstacleDetection {
  late ObstacleDistance obDist;
  late ObstacleDirection obDirect;
  ITIScodes? description = null;
  GenericLocations? locationDetails = null;
  late DDateTime dateTime;
  VerticalAccelerationThreshold? vertEvent = null;
  ObstacleDetection.fromC(C.ObstacleDetection c_obj) {
    obDist = ObstacleDistance(c_obj.obDist);
    obDirect = ObstacleDirection(c_obj.obDirect);
    if (c_obj.description.address != 0) {
      description = ITIScodes(c_obj.description.value);
    }

    if (c_obj.locationDetails.address != 0) {
      locationDetails = GenericLocations.values[c_obj.locationDetails.value];
    }

    dateTime = DDateTime.fromC(c_obj.dateTime);
    if (c_obj.vertEvent.address != 0) {
      vertEvent = VerticalAccelerationThreshold.fromBitString(c_obj.vertEvent.ref);
    }
  }
}
