/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'dart:ffi';

import 'package:asn1_plugin/generated_bindings.dart' as C;

class PrivilegedEventFlags {
  PrivilegedEventFlags(C.BIT_STRING_s value);

  late bool peUnavailable;
  late bool peEmergencyResponse;
  late bool peEmergencyLightsActive;
  late bool peEmergencySoundActive;
  late bool peNonEmergencySoundActive;

  PrivilegedEventFlags.fromBitString(C.BIT_STRING_s bits) {
    List<int> decodedBits = bits.buf.asTypedList(bits.size);

    peUnavailable = (decodedBits[0] & (1 << 0)) != 0;
    peEmergencyResponse = (decodedBits[0] & (1 << 1)) != 0;
    peEmergencyLightsActive = (decodedBits[0] & (1 << 2)) != 0;
    peEmergencySoundActive = (decodedBits[0] & (1 << 3)) != 0;
    peNonEmergencySoundActive = (decodedBits[0] & (1 << 3)) != 0;
  }
}
