/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/basic_vehicle_role.dart';
import 'package:asn1_plugin/j2735/2024/common/iso3833vehicle_type.dart';
import 'package:asn1_plugin/j2735/2024/common/request_importance_level.dart';
import 'package:asn1_plugin/j2735/2024/common/request_sub_role.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_type.dart';

class RequestorType {
  late BasicVehicleRole role;
  RequestSubRole? subrole = null;
  RequestImportanceLevel? request = null;
  Iso3833VehicleType? iso3883 = null;
  VehicleType? hpmsType = null;

  RequestorType.fromC(C.RequestorType c_obj) {
    role = BasicVehicleRole.values[c_obj.role];
    if (c_obj.subrole.address != 0) {
      subrole = RequestSubRole.values[c_obj.subrole.value];
    }

    if (c_obj.request.address != 0) {
      request = RequestImportanceLevel.values[c_obj.request.value];
    }

    if (c_obj.iso3883.address != 0) {
      iso3883 = Iso3833VehicleType(c_obj.iso3883.value);
    }

    if (c_obj.hpmsType.address != 0) {
      hpmsType = VehicleType.values[c_obj.hpmsType.value];
    }
  }
}
