/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/mean_variation.dart';
import 'package:asn1_plugin/j2735/2024/common/variation_std_dev.dart';

class RoadRoughness {
  late MeanVariation meanVerticalVariation;
  VariationStdDev? verticalVariationStdDev = null;
  MeanVariation? meanHorizontalVariation = null;
  VariationStdDev? horizontalVariationStdDev = null;
  RoadRoughness.fromC(C.RoadRoughness c_obj) {
    meanVerticalVariation = MeanVariation(c_obj.meanVerticalVariation);
    if (c_obj.verticalVariationStdDev.address != 0) {
      verticalVariationStdDev = VariationStdDev(c_obj.verticalVariationStdDev.value);
    }

    if (c_obj.meanHorizontalVariation.address != 0) {
      meanHorizontalVariation = MeanVariation(c_obj.meanHorizontalVariation.value);
    }

    if (c_obj.horizontalVariationStdDev.address != 0) {
      horizontalVariationStdDev = VariationStdDev(c_obj.horizontalVariationStdDev.value);
    }
  }
}
