/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

class SchoolBusJ2945Slash1C {
  late bool flashingAmberLights;
  late bool flashingRedLights;
  bool? studentsCrossingFront = null;
  bool? studentsCrossingBehind = null;
  bool? studentsLoading = null;
  bool? studentsUnloading = null;
  bool? wheelchairLiftInUse = null;
  bool? emergencyExitOpen = null;
  bool? emergencyRequestMedical = null;
  bool? emergencyRequestFire = null;
  bool? emergencyRequestPolice = null;
  SchoolBusJ2945Slash1C.fromC(C.SchoolBusJ2945Slash1C c_obj) {
    flashingAmberLights = c_obj.flashingAmberLights == 1;
    flashingRedLights = c_obj.flashingRedLights == 1;
    if (c_obj.studentsCrossingFront.address != 0) {
      studentsCrossingFront = c_obj.studentsCrossingFront.value == 1;
    }

    if (c_obj.studentsCrossingBehind.address != 0) {
      studentsCrossingBehind = c_obj.studentsCrossingBehind.value == 1;
    }

    if (c_obj.studentsLoading.address != 0) {
      studentsLoading = c_obj.studentsLoading.value == 1;
    }

    if (c_obj.studentsUnloading.address != 0) {
      studentsUnloading = c_obj.studentsUnloading.value == 1;
    }

    if (c_obj.wheelchairLiftInUse.address != 0) {
      wheelchairLiftInUse = c_obj.wheelchairLiftInUse.value == 1;
    }

    if (c_obj.emergencyExitOpen.address != 0) {
      emergencyExitOpen = c_obj.emergencyExitOpen.value == 1;
    }

    if (c_obj.emergencyRequestMedical.address != 0) {
      emergencyRequestMedical = c_obj.emergencyRequestMedical.value == 1;
    }

    if (c_obj.emergencyRequestFire.address != 0) {
      emergencyRequestFire = c_obj.emergencyRequestFire.value == 1;
    }

    if (c_obj.emergencyRequestPolice.address != 0) {
      emergencyRequestPolice = c_obj.emergencyRequestPolice.value == 1;
    }
  }
}
