/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/vehicle_width.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_length.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_height.dart';
import 'package:asn1_plugin/j2735/2024/common/trailer_weight.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/pivot_point_description.dart';
import 'package:asn1_plugin/j2735/2024/common/bumper_heights.dart';
import 'package:asn1_plugin/j2735/2024/common/axles.dart';

class TrailerUnitDescJ2945Slash1B {
  late VehicleWidth width;
  late VehicleLength length;
  VehicleHeight? height = null;
  TrailerWeight? weight = null;
  late PivotPointDescription frontPivot;
  PivotPointDescription? rearPivot = null;
  BumperHeights? bumpers = null;
  Axles? axles = null;
  TrailerUnitDescJ2945Slash1B.fromC(C.TrailerUnitDescJ2945Slash1B c_obj) {
    width = VehicleWidth(c_obj.width);
    length = VehicleLength(c_obj.length);
    if (c_obj.height.address != 0) {
      height = VehicleHeight(c_obj.height.value);
    }

    if (c_obj.weight.address != 0) {
      weight = TrailerWeight(c_obj.weight.value);
    }

    frontPivot = PivotPointDescription.fromC(c_obj.frontPivot);
    if (c_obj.rearPivot.address != 0) {
      rearPivot = PivotPointDescription.fromC(c_obj.rearPivot.ref);
    }

    if (c_obj.bumpers.address != 0) {
      bumpers = BumperHeights.fromC(c_obj.bumpers.ref);
    }

    if (c_obj.axles.address != 0) {
      axles = Axles.fromC(c_obj.axles.ref);
    }
  }
}
