/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

class VehicleMass {
  late int mass;
  VehicleMass(int mass);

  int getMassKg() {
    if (mass >= 0 && mass <= 80) {
      return mass * 50;
    } else if (mass >= 81 && mass <= 200) {
      return 4000 + (mass - 80) * 500;
    } else if (mass >= 200) {
      return 64000 + (mass - 200) * 2000;
    }
    return 17000;
  }
}
