/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/vehicle_height.dart';
import 'package:asn1_plugin/j2735/2024/common/bumper_heights.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_mass.dart';
import 'package:asn1_plugin/j2735/2024/common/trailer_weight.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/pivot_point_description.dart';
import 'package:asn1_plugin/j2735/2024/common/axles.dart';

class VehicleData {
  VehicleHeight? height = null;
  BumperHeights? bumpers = null;
  VehicleMass? mass = null;
  TrailerWeight? doNotUse = null;
  bool trailerPresent = false;
  PivotPointDescription? pivotPoint = null;
  Axles? axles = null;
  LeanAngleInteger? leanAngle = null;
  VehicleData.fromC(C.VehicleData c_obj) {
    if (c_obj.height.address != 0) {
      height = VehicleHeight(c_obj.height.value);
    }

    if (c_obj.bumpers.address != 0) {
      bumpers = BumperHeights.fromC(c_obj.bumpers.ref);
    }

    if (c_obj.mass.address != 0) {
      mass = VehicleMass(c_obj.mass.value);
    }

    if (c_obj.doNotUse.address != 0) {
      doNotUse = TrailerWeight(c_obj.doNotUse.value);
    }

    if (c_obj.trailerPresent.address != 0) {
      trailerPresent = c_obj.trailerPresent.value == 1;
    }

    if (c_obj.pivotPoint.address != 0) {
      pivotPoint = PivotPointDescription.fromC(c_obj.pivotPoint.ref);
    }

    if (c_obj.axles.address != 0) {
      axles = Axles.fromC(c_obj.axles.ref);
    }

    if (c_obj.leanAngle.address != 0) {
      leanAngle = LeanAngleInteger(c_obj.leanAngle.value);
    }
  }
}

class LeanAngleInteger {
  late int leanAngleInteger;
  LeanAngleInteger(this.leanAngleInteger);
}
