/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/basic_vehicle_class.dart';
import 'package:asn1_plugin/j2735/2024/common/basic_vehicle_role.dart';
import 'package:asn1_plugin/j2735/2024/common/iso3833vehicle_type.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_type.dart';
import 'package:asn1_plugin/j2735/2024/itis/vehicle_group_affected.dart';
import 'package:asn1_plugin/j2735/2024/itis/incident_response_equipment.dart';
import 'package:asn1_plugin/j2735/2024/itis/responder_group_affected.dart';
import 'package:asn1_plugin/j2735/2024/common/fuel_type.dart';

class VehicleClassification {
  BasicVehicleClass? keyType = null;
  BasicVehicleRole? role = null;
  Iso3833VehicleType? iso3883 = null;
  VehicleType? hpmsType = null;
  VehicleGroupAffected? vehicleType = null;
  IncidentResponseEquipment? responseEquip = null;
  ResponderGroupAffected? responderType = null;
  FuelType? fuelType = null;
  VehicleClassification.fromC(C.VehicleClassification c_obj) {
    if (c_obj.keyType.address != 0) {
      keyType = BasicVehicleClass(c_obj.keyType.value);
    }

    if (c_obj.role.address != 0) {
      role = BasicVehicleRole.values[c_obj.role.value];
    }

    if (c_obj.iso3883.address != 0) {
      iso3883 = Iso3833VehicleType(c_obj.iso3883.value);
    }

    if (c_obj.hpmsType.address != 0) {
      hpmsType = VehicleType.values[c_obj.hpmsType.value];
    }

    if (c_obj.vehicleType.address != 0) {
      vehicleType = VehicleGroupAffected.values[c_obj.vehicleType.value];
    }

    if (c_obj.responseEquip.address != 0) {
      responseEquip = IncidentResponseEquipment.values[c_obj.responseEquip.value];
    }

    if (c_obj.responderType.address != 0) {
      responderType = ResponderGroupAffected.values[c_obj.responderType.value];
    }

    if (c_obj.fuelType.address != 0) {
      fuelType = FuelType(c_obj.fuelType.value);
    }
  }
}
