/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

class VerticalAccelerationThreshold {
  late bool notEquipped;
  late bool leftFront;
  late bool leftRear;
  late bool rightFront;
  late bool rightRear;

  VerticalAccelerationThreshold.fromBitString(C.BIT_STRING_s bits) {
    List<int> decodedBits = bits.buf.asTypedList(bits.size);

    notEquipped = (decodedBits[0] & (1 << 7)) != 0;
    leftFront = (decodedBits[0] & (1 << 6)) != 0;
    leftRear = (decodedBits[0] & (1 << 5)) != 0;
    rightFront = (decodedBits[0] & (1 << 4)) != 0;
    rightRear = (decodedBits[0] & (1 << 3)) != 0;
  }
}
