/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/ambient_air_temperature.dart';
import 'package:asn1_plugin/j2735/2024/common/ambient_air_pressure.dart';
import 'package:asn1_plugin/j2735/2024/common/wiper_set.dart';

class WeatherProbe {
  AmbientAirTemperature? airTemp = null;
  AmbientAirPressure? airPressure = null;
  WiperSet? rainRates = null;
  WeatherProbe.fromC(C.WeatherProbe c_obj) {
    if (c_obj.airTemp.address != 0) {
      airTemp = AmbientAirTemperature(c_obj.airTemp.value);
    }

    if (c_obj.airPressure.address != 0) {
      airPressure = AmbientAirPressure(c_obj.airPressure.value);
    }

    if (c_obj.rainRates.address != 0) {
      rainRates = WiperSet.fromC(c_obj.rainRates.ref);
    }
  }
}
