/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/wiper_status.dart';
import 'package:asn1_plugin/j2735/2024/common/wiper_rate.dart';

class WiperSet {
  late WiperStatus statusFront;
  late WiperRate rateFront;
  WiperStatus? statusRear = null;
  WiperRate? rateRear = null;
  WiperSet.fromC(C.WiperSet c_obj) {
    statusFront = WiperStatus.values[c_obj.statusFront];
    rateFront = WiperRate(c_obj.rateFront);
    if (c_obj.statusRear.address != 0) {
      statusRear = WiperStatus.values[c_obj.statusRear.value];
    }

    if (c_obj.rateRear.address != 0) {
      rateRear = WiperRate(c_obj.rateRear.value);
    }
  }
}
