/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/choice/choice_charges_table.dart';
import 'package:asn1_plugin/j3217/2022/choice/choice_toll_type_charge.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/axles_charges_table.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/veh_type_charges_table.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/weight_charges_table.dart';


class ChargesTable extends Choice_TollTypeCharge{
  late VehTypeChargesTable vehTypeBased; 
  late AxlesChargesTable numAxlesBased; 
  late WeightChargesTable weightBased; 
  late ChargesTableChoice chargesTableChoice;
  ChargesTable.fromC(C.ChargesTable c_obj){
    chargesTableChoice = ChargesTableChoice.fromC(c_obj);
  }
}

class ChargesTableChoice {
  late Choice_ChargesTable chargesTableChoice;
  ChargesTableChoice.fromC(C.ChargesTable c_chargesTable) {
    if (c_chargesTable.present == C.ChargesTable_PR.ChargesTable_PR_vehTypeBased) {
      chargesTableChoice = VehTypeChargesTable.fromC(c_chargesTable.choice.vehTypeBased);
    } else if (c_chargesTable.present == C.ChargesTable_PR.ChargesTable_PR_numAxlesBased) {
      chargesTableChoice = AxlesChargesTable.fromC(c_chargesTable.choice.numAxlesBased);
    } else if (c_chargesTable.present == C.ChargesTable_PR.ChargesTable_PR_weightBased) {
      chargesTableChoice = WeightChargesTable.fromC(c_chargesTable.choice.weightBased);
    }
  }
}
