/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/choice/choice_weight_charge.dart';
import 'package:asn1_plugin/j3217/2022/payment_fee.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/weight_limit_units.dart';


class PerAxleWeightCharges extends Choice_WeightCharge{
    late TotalWeightLimitInteger totalWeightLimit; 
    late MaxLadenWeightOnAxleInteger maxLadenWeightOnAxle; 
    late WeightLimitUnits weightLimitUnits; 
    late PaymentFee axleWeightCharge; 
    PerAxleWeightCharges.fromC(C.PerAxleWeightCharges c_obj){
        totalWeightLimit = TotalWeightLimitInteger(c_obj.totalWeightLimit);
        maxLadenWeightOnAxle = MaxLadenWeightOnAxleInteger(c_obj.maxLadenWeightOnAxle);
        weightLimitUnits = WeightLimitUnits.values[c_obj.weightLimitUnits];
        axleWeightCharge = PaymentFee.fromC(c_obj.axleWeightCharge);
    }
}
class TotalWeightLimitInteger {
    late int totalWeightLimitInteger;
    TotalWeightLimitInteger(int value): totalWeightLimitInteger = value;
}


class MaxLadenWeightOnAxleInteger {
    late int maxLadenWeightOnAxleInteger;
    MaxLadenWeightOnAxleInteger(int value): maxLadenWeightOnAxleInteger = value;
}


