/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi'; 
import 'package:asn1_plugin/j2735/2024/common/position_3d.dart'; 
import 'package:asn1_plugin/j2735/2024/common/regulatory_speed_limit.dart';
import 'package:asn1_plugin/j2735/2024/common/lane_width.dart';
import 'package:asn1_plugin/j2735/2024/map_data/generic_lane.dart';


class TollPointMap{
  late RevisionNumInteger revisionNum; 
  late Position3D referencePoint; 
  late RegulatorySpeedLimit speedLimit; 
  late LaneWidth laneWidth; 
  late ApproachLanesMap approachLanesMap; 
  late TollZoneLanesMap tollZoneLanesMap; 
  TollPointMap.fromC(C.TollPointMap c_obj){
      revisionNum = RevisionNumInteger(c_obj.revisionNum);
      referencePoint = Position3D.fromC(c_obj.referencePoint);
      speedLimit = RegulatorySpeedLimit.fromC(c_obj.speedLimit);
      laneWidth = LaneWidth(c_obj.laneWidth);
      approachLanesMap = ApproachLanesMap.fromC(c_obj.approachLanesMap);
      tollZoneLanesMap = TollZoneLanesMap.fromC(c_obj.tollZoneLanesMap);
  }
}
class RevisionNumInteger{
  late int revisionNumInteger;
  RevisionNumInteger(int value): revisionNumInteger = value;
}

class ApproachLanesMap {
  late List<GenericLane> approachLanesMap;
  ApproachLanesMap.fromC(C.TollPointMap__approachLanesMap c_approachLanesMap) : super() {
    approachLanesMap = [];
    for (int i = 0; i < c_approachLanesMap.list.count; i++) {
      approachLanesMap.add(GenericLane.fromC(c_approachLanesMap.list.array[i].ref));
    }
  }
}

class TollZoneLanesMap {
  late List<GenericLane> tollZoneLanesMap;
  TollZoneLanesMap.fromC(C.TollPointMap__tollZoneLanesMap c_tollZoneLanesMap) : super() {
    tollZoneLanesMap = [];
    for (int i = 0; i < c_tollZoneLanesMap.list.count; i++) {
      tollZoneLanesMap.add(GenericLane.fromC(c_tollZoneLanesMap.list.array[i].ref));
    }
  }
}


