/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/generated_bindings.dart';
import 'package:asn1_plugin/j2735/2024/common/descriptive_name.dart';
import 'dart:ffi';

import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/toll_point_id.dart';
import 'package:ffi/ffi.dart';

class TollChargerInfo{
    late int tollChargerId;
    late TollPointID tollPointId; 
    DescriptiveName? descriptiveName; 

    TollChargerInfo.fromC(C.TollChargerInfo c_obj){
        tollChargerId = _oidBufferToInt(c_obj.tollChargerId);
        tollPointId = TollPointID(c_obj.tollPointId);
        if(c_obj.descriptiveName.address != 0){
            descriptiveName = DescriptiveName.fromOctetString(c_obj.descriptiveName.ref);
        }
    }

    C.TollChargerInfo toC(Pointer<C.TollChargerInfo> pointer) {
      final c_info = pointer.ref;
      c_info.tollChargerId = intToAsnPrimitiveType(tollChargerId); 
      c_info.tollPointId = tollPointId.tollPointID;
      if(descriptiveName != null){
        //c_info.descriptiveName = descriptiveName!.toC(calloc.allocate<C.OCTET_STRING>(sizeOf<C.OCTET_STRING>()));
      }
      return c_info;
    }

    // C.TollUsageMessage toC(TollUsageMessage tum, Pointer<C.TollUsageMessage> pointer) {
    //   final c_tum = pointer.ref;
    //   c_tum.tollPointInfo = tum.tollPointInfo.toC(calloc.allocate<C.TollChargerInfo>(sizeOf<C.TollChargerInfo>()));
    //   c_tum.tempID = tum.tempID.toC(calloc.allocate<C.OCTET_STRING>(sizeOf<C.OCTET_STRING>()));
    //   c_tum.tumSequenceNum = 0;
    //   c_tum.tamSequenceNum = 0;
    //   if(tum.tumHash != null){
    //     //Cookie - ToDo
    //   }
    //   c_tum.encryptedTumData = tum.encryptedTumData.toC(calloc.allocate<C.OCTET_STRING>(sizeOf<C.OCTET_STRING>()));
    //   return c_tum;
    // }

    int _oidBufferToInt(ASN__PRIMITIVE_TYPE_s oid){
        // Assuming the OID represents an integer in its buffer
        // Convert the buffer to an integer
        int result = 0;
        for(int i = 0; i < oid.size; i++){
            result = (result << 8) | oid.buf.elementAt(i).value;
        }
        return result;
    }

    ASN__PRIMITIVE_TYPE_s intToAsnPrimitiveType(int value) {
      // Convert int to big-endian byte array
      List<int> bytes = [];
      int temp = value;
      do {
        bytes.insert(0, temp & 0xFF);
        temp >>= 8;
      } while (temp > 0);

      // Allocate the struct and buffer
      final ptr = calloc<ASN__PRIMITIVE_TYPE_s>();
      final buf = malloc.allocate<Uint8>(bytes.length);

      for (int i = 0; i < bytes.length; i++) {
        buf[i] = bytes[i];
      }

      ptr.ref.buf = buf;
      ptr.ref.size = bytes.length;

      return ptr.ref;
    }
}
