/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j3217/2022/choice/choice_weight_charge.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/per_axle_weight_charges.dart';
import 'package:asn1_plugin/j3217/2022/toll_advertisement_message/total_weight_charges.dart';
 


class WeightCharges{
    late WeightChargesChoice weightCharge;
    WeightCharges.fromC(C.WeightCharges c_obj){
      weightCharge = WeightChargesChoice.fromC(c_obj);
    }
}

class WeightChargesChoice{ 
  late Choice_WeightCharge weightChargesChoice;
  WeightChargesChoice.fromC(C.WeightCharges c_weightCharges) {
    if (c_weightCharges.present == C.WeightCharges_PR.WeightCharges_PR_totalWeightCharges) {
      weightChargesChoice = TotalWeightCharges.fromC(c_weightCharges.choice.totalWeightCharges);
    } else if (c_weightCharges.present == C.WeightCharges_PR.WeightCharges_PR_perAxleWeightCharges) {
      weightChargesChoice = PerAxleWeightCharges.fromC(c_weightCharges.choice.perAxleWeightCharges);
    }
  }
}
