/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/itis/itis_codes.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/itis/generic_locations.dart';

class DisabledVehicle {
  late ITIScodes statusDetails;
  GenericLocations? locationDetails = null;
  DisabledVehicle.fromC(C.DisabledVehicle c_obj) {
    statusDetails = ITIScodes(c_obj.statusDetails);
    if (c_obj.locationDetails.address != 0) {
      locationDetails = GenericLocations.values[c_obj.locationDetails.value];
    }
  }
}
