/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/itiscodes.dart';
import 'package:asn1_plugin/j2735/2024/common/priority.dart';
import 'package:asn1_plugin/j2735/2024/common/heading_slice.dart';
import 'package:asn1_plugin/j2735/2024/common/extent.dart';

class EventDescription {
  late ITIScodes typeEvent;
  List<ITIScodes>? description = null;
  Priority? priority = null;
  HeadingSlice? heading = null;
  Extent? extent = null;
  EventDescription.fromC(C.EventDescription c_obj) {
    typeEvent = ITIScodes(c_obj.typeEvent);
    if (c_obj.description.address != 0) {
      description = [];

      for (int i = 0; i < c_obj.description.ref.list.count; i++) {
        this.description!.add(ITIScodes(c_obj.description.ref.list.array[i].value));
      }
    }

    if (c_obj.priority.address != 0) {
      priority = Priority(c_obj.priority.ref);
    }

    if (c_obj.heading.address != 0) {
      heading = HeadingSlice.fromBitString(c_obj.heading.ref);
    }

    if (c_obj.extent.address != 0) {
      extent = Extent.values[c_obj.extent.value];
    }
  }
}
