/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/basic_safety_message/bsmpart_iiextension.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/emergency_details.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/event_description.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/trailer_data.dart';

class SpecialVehicleExtensions extends BSMpartIIExtension {
  EmergencyDetails? vehicleAlerts = null;
  EventDescription? description = null;
  TrailerData? doNotUse = null;
  SpecialVehicleExtensions.fromC(C.SpecialVehicleExtensions c_obj) {
    if (c_obj.vehicleAlerts.address != 0) {
      vehicleAlerts = EmergencyDetails.fromC(c_obj.vehicleAlerts.ref);
    }

    if (c_obj.description.address != 0) {
      description = EventDescription.fromC(c_obj.description.ref);
    }

    if (c_obj.doNotUse.address != 0) {
      doNotUse = TrailerData.fromC(c_obj.doNotUse.ref);
    }
  }
}
