/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'package:asn1_plugin/j2735/2024/basic_safety_message/bsmpart_iiextension.dart';
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/basic_vehicle_class.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_classification.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/vehicle_data.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/weather_report.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/weather_probe.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/obstacle_detection.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/disabled_vehicle.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/speed_profile.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/rtcmpackage.dart';
import 'package:asn1_plugin/j2735/2024/probe_data_report/rpt_vehicle_class.dart';
import 'package:asn1_plugin/j2735/2024/common/trailers_j2945slash1b.dart';
import 'package:asn1_plugin/j2735/2024/common/school_bus_j2945slash1c.dart';

class SupplementalVehicleExtensions extends BSMpartIIExtension {
  BasicVehicleClass? classification = null;
  VehicleClassification? classDetails = null;
  VehicleData? vehicleData = null;
  WeatherReport? doNotUse1 = null;
  WeatherProbe? doNotUse2 = null;
  ObstacleDetection? doNotUse3 = null;
  DisabledVehicle? status = null;
  SpeedProfile? doNotUse4 = null;
  RTCMPackage? doNotUse5 = null;
  late RptVehicleClass fhwaVehicleClass;
  TrailersJ2945Slash1B? trailers = null;
  SchoolBusJ2945Slash1C? schoolBus = null;
  SupplementalVehicleExtensions.fromC(C.SupplementalVehicleExtensions c_obj) {
    if (c_obj.classification.address != 0) {
      classification = BasicVehicleClass(c_obj.classification.value);
    }

    if (c_obj.classDetails.address != 0) {
      classDetails = VehicleClassification.fromC(c_obj.classDetails.ref);
    }

    if (c_obj.vehicleData.address != 0) {
      vehicleData = VehicleData.fromC(c_obj.vehicleData.ref);
    }

    if (c_obj.doNotUse1.address != 0) {
      doNotUse1 = WeatherReport.fromC(c_obj.doNotUse1.ref);
    }

    if (c_obj.doNotUse2.address != 0) {
      doNotUse2 = WeatherProbe.fromC(c_obj.doNotUse2.ref);
    }

    if (c_obj.doNotUse3.address != 0) {
      doNotUse3 = ObstacleDetection.fromC(c_obj.doNotUse3.ref);
    }

    if (c_obj.status.address != 0) {
      status = DisabledVehicle.fromC(c_obj.status.ref);
    }

    if (c_obj.doNotUse4.address != 0) {
      doNotUse4 = SpeedProfile.fromC(c_obj.doNotUse4.ref);
    }

    if (c_obj.doNotUse5.address != 0) {
      doNotUse5 = RTCMPackage.fromC(c_obj.doNotUse5.ref);
    }

    if (c_obj.fhwaVehicleClass.address != 0) {
      fhwaVehicleClass = RptVehicleClass.values[c_obj.fhwaVehicleClass.value];
    }

    if (c_obj.trailers.address != 0) {
      trailers = TrailersJ2945Slash1B.fromC(c_obj.trailers.ref);
    }

    if (c_obj.schoolBus.address != 0) {
      schoolBus = SchoolBusJ2945Slash1C.fromC(c_obj.schoolBus.ref);
    }
  }
}
