/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/sspindex.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/pivot_point_description.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/trailer_unit_description_list.dart';

class TrailerData {
  late SSPindex doNotUse;
  late PivotPointDescription connection;
  late TrailerUnitDescriptionList units;
  TrailerData.fromC(C.TrailerData c_obj) {
    doNotUse = SSPindex(c_obj.doNotUse);
    connection = PivotPointDescription.fromC(c_obj.connection);
    units = TrailerUnitDescriptionList.fromC(c_obj.units);
  }
}
