/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/is_dolly.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_width.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_length.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_height.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/trailer_mass.dart';
import 'package:asn1_plugin/j2735/2024/common/bumper_heights.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/pivot_point_description.dart';
import 'package:asn1_plugin/j2735/2024/common/offset_b12.dart';
import 'package:asn1_plugin/j2735/2024/common/node_xy_24b.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/vert_offset_b07.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/trailer_history_point_list.dart';

class TrailerUnitDescription {
  late IsDolly isDolly;
  late VehicleWidth width;
  late VehicleLength length;
  VehicleHeight? height = null;
  TrailerMass? mass = null;
  BumperHeights? bumperHeights = null;
  VehicleHeight? centerOfGravity = null;
  late PivotPointDescription frontPivot;
  PivotPointDescription? rearPivot = null;
  Offset_B12? rearWheelOffset = null;
  late Node_XY_24b positionOffset;
  VertOffset_B07? elevationOffset = null;
  TrailerHistoryPointList? crumbData = null;
  TrailerUnitDescription.fromC(C.TrailerUnitDescription c_obj) {
    isDolly = IsDolly(c_obj.isDolly == 1);
    width = VehicleWidth(c_obj.width);
    length = VehicleLength(c_obj.length);
    if (c_obj.height.address != 0) {
      height = VehicleHeight(c_obj.height.value);
    }

    if (c_obj.mass.address != 0) {
      mass = TrailerMass(c_obj.mass.value);
    }

    if (c_obj.bumperHeights.address != 0) {
      bumperHeights = BumperHeights.fromC(c_obj.bumperHeights.ref);
    }

    if (c_obj.centerOfGravity.address != 0) {
      centerOfGravity = VehicleHeight(c_obj.centerOfGravity.value);
    }

    frontPivot = PivotPointDescription.fromC(c_obj.frontPivot);
    if (c_obj.rearPivot.address != 0) {
      rearPivot = PivotPointDescription.fromC(c_obj.rearPivot.ref);
    }

    if (c_obj.rearWheelOffset.address != 0) {
      rearWheelOffset = Offset_B12(c_obj.rearWheelOffset.value);
    }

    positionOffset = Node_XY_24b.fromC(c_obj.positionOffset);
    if (c_obj.elevationOffset.address != 0) {
      elevationOffset = VertOffset_B07(c_obj.elevationOffset.value);
    }

    if (c_obj.crumbData.address != 0) {
      crumbData = TrailerHistoryPointList.fromC(c_obj.crumbData.ref);
    }
  }
}
