/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/angle.dart';
import 'package:asn1_plugin/j2735/2024/common/time_offset.dart';
import 'package:asn1_plugin/j2735/2024/common/node_xy_24b.dart';
import 'package:asn1_plugin/j2735/2024/basic_safety_message/vert_offset_b07.dart';
import 'package:asn1_plugin/j2735/2024/common/coarse_heading.dart';

class TrailerHistoryPoint {
  late Angle pivotAngle;
  late TimeOffset timeOffset;
  late Node_XY_24b positionOffset;
  VertOffset_B07? elevationOffset = null;
  CoarseHeading? heading = null;
  TrailerHistoryPoint.fromC(C.TrailerHistoryPoint c_obj) {
    pivotAngle = Angle(c_obj.pivotAngle);
    timeOffset = TimeOffset(c_obj.timeOffset);
    positionOffset = Node_XY_24b.fromC(c_obj.positionOffset);
    if (c_obj.elevationOffset.address != 0) {
      elevationOffset = VertOffset_B07(c_obj.elevationOffset.value);
    }

    if (c_obj.heading.address != 0) {
      heading = CoarseHeading(c_obj.heading.value);
    }
  }
}
