/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';

class VehicleEventFlags {
  late bool eventHazardLights;
  late bool eventStopLineViolation;
  late bool eventABSactivated;
  late bool eventTractionControlLoss;
  late bool eventStabilityControlactivated;
  late bool eventHazardousMaterials;
  late bool eventReserved1;
  late bool eventHardBraking;
  late bool eventLightsChanged;
  late bool eventWipersChanged;
  late bool eventFlatTire;
  late bool eventDisabledVehicle;
  late bool eventAirBagDeployment;
  late bool eventJackKnife;

  VehicleEventFlags.fromBitString(C.BIT_STRING_s bits) {
    List<int> decodedBits = bits.buf.asTypedList(bits.size);

    eventHazardLights = (decodedBits[1] & (1 << 7)) != 0;
    eventStopLineViolation = (decodedBits[1] & (1 << 6)) != 0;
    eventABSactivated = (decodedBits[1] & (1 << 5)) != 0;
    eventTractionControlLoss = (decodedBits[1] & (1 << 4)) != 0;
    eventStabilityControlactivated = (decodedBits[1] & (1 << 3)) != 0;
    eventHazardousMaterials = (decodedBits[1] & (1 << 2)) != 0;
    eventReserved1 = (decodedBits[1] & (1 << 1)) != 0;
    eventHardBraking = (decodedBits[1] & (1 << 0)) != 0;

    eventLightsChanged = (decodedBits[0] & (1 << 7)) != 0;
    eventWipersChanged = (decodedBits[0] & (1 << 6)) != 0;
    eventFlatTire = (decodedBits[0] & (1 << 5)) != 0;
    eventDisabledVehicle = (decodedBits[0] & (1 << 4)) != 0;
    eventAirBagDeployment = (decodedBits[0] & (1 << 3)) != 0;
    eventJackKnife = (decodedBits[0] & (1 << 2)) != 0;
  }

  VehicleEventFlags(C.BIT_STRING_s value);
}
