/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/ntcip/ess_precip_yes_no.dart';
import 'package:asn1_plugin/j2735/2024/ntcip/ess_precip_rate.dart';
import 'package:asn1_plugin/j2735/2024/ntcip/ess_precip_situation.dart';
import 'package:asn1_plugin/j2735/2024/ntcip/ess_solar_radiation.dart';
import 'package:asn1_plugin/j2735/2024/ntcip/ess_mobile_friction.dart';
import 'package:asn1_plugin/j2735/2024/common/coefficient_of_friction.dart';

class WeatherReport {
  late EssPrecipYesNo isRaining;
  EssPrecipRate? rainRate = null;
  EssPrecipSituation? precipSituation = null;
  EssSolarRadiation? solarRadiation = null;
  EssMobileFriction? friction = null;
  CoefficientOfFriction? roadFriction = null;
  WeatherReport.fromC(C.WeatherReport c_obj) {
    isRaining = EssPrecipYesNo.values[c_obj.isRaining];
    if (c_obj.rainRate.address != 0) {
      rainRate = EssPrecipRate(c_obj.rainRate.value);
    }

    if (c_obj.precipSituation.address != 0) {
      precipSituation = EssPrecipSituation.values[c_obj.precipSituation.value];
    }

    if (c_obj.solarRadiation.address != 0) {
      solarRadiation = EssSolarRadiation(c_obj.solarRadiation.value);
    }

    if (c_obj.friction.address != 0) {
      friction = EssMobileFriction(c_obj.friction.value);
    }

    if (c_obj.roadFriction.address != 0) {
      roadFriction = CoefficientOfFriction(c_obj.roadFriction.value);
    }
  }
}
