/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/descriptive_name.dart';
import 'package:asn1_plugin/j2735/2024/common/requestor_type.dart';
import 'package:asn1_plugin/j2735/2024/common/vehicle_id.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/delta_time.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/requestor_position_vector.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/transit_vehicle_occupancy.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/transit_vehicle_status.dart';

class RequestorDescription {
  late VehicleID id;
  RequestorType? type = null;
  RequestorPositionVector? position = null;
  DescriptiveName? name = null;
  DescriptiveName? routeName = null;
  TransitVehicleStatus? transitStatus = null;
  TransitVehicleOccupancy? transitOccupancy = null;
  DeltaTime? transitSchedule = null;

  RequestorDescription.fromC(C.RequestorDescription c_obj) {
    id = VehicleID.fromC(c_obj.id);
    if (c_obj.type.address != 0) {
      type = RequestorType.fromC(c_obj.type.ref);
    }

    if (c_obj.position.address != 0) {
      position = RequestorPositionVector.fromC(c_obj.position.ref);
    }

    if (c_obj.name.address != 0) {
      name = DescriptiveName.fromOctetString(c_obj.name.ref);
    }

    if (c_obj.routeName.address != 0) {
      routeName = DescriptiveName.fromOctetString(c_obj.routeName.ref);
    }

    if (c_obj.transitStatus.address != 0) {
      transitStatus = TransitVehicleStatus.fromBitString(c_obj.transitStatus.ref);
    }

    if (c_obj.transitOccupancy.address != 0) {
      transitOccupancy = TransitVehicleOccupancy.values[c_obj.transitOccupancy.value];
    }

    if (c_obj.transitSchedule.address != 0) {
      transitSchedule = DeltaTime(c_obj.transitSchedule.value);
    }
  }
}
