/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/angle.dart';
import 'package:asn1_plugin/j2735/2024/common/position_3d.dart';
import 'package:asn1_plugin/j2735/2024/common/transmission_and_speed.dart';

class RequestorPositionVector {
  late Position3D position;
  Angle? heading = null;
  TransmissionAndSpeed? speed = null;
  RequestorPositionVector.fromC(C.RequestorPositionVector c_obj) {
    position = Position3D.fromC(c_obj.position);
    if (c_obj.heading.address != 0) {
      heading = Angle(c_obj.heading.value);
    }

    if (c_obj.speed.address != 0) {
      speed = TransmissionAndSpeed.fromC(c_obj.speed.ref);
    }
  }
}
