/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/d_second.dart';
import 'package:asn1_plugin/j2735/2024/common/minute_of_the_year.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/signal_request.dart';

class SignalRequestPackage {
  late SignalRequest request;
  MinuteOfTheYear? minute = null;
  DSecond? second = null;
  DSecond? duration = null;

  SignalRequestPackage.fromC(C.SignalRequestPackage c_obj) {
    request = SignalRequest.fromC(c_obj.request);
    if (c_obj.minute.address != 0) {
      minute = MinuteOfTheYear(c_obj.minute.value);
    }

    if (c_obj.second.address != 0) {
      second = DSecond(c_obj.second.value);
    }

    if (c_obj.duration.address != 0) {
      duration = DSecond(c_obj.duration.value);
    }
  }
}
