/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

import 'package:asn1_plugin/generated_bindings.dart' as C;
import 'dart:ffi';
import 'package:asn1_plugin/j2735/2024/common/intersection_reference_id.dart';
import 'package:asn1_plugin/j2735/2024/common/request_id.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/intersection_access_point.dart';
import 'package:asn1_plugin/j2735/2024/signal_request_message/priority_request_type.dart';

class SignalRequest {
  late IntersectionReferenceID id;
  late RequestID requestID;
  late PriorityRequestType requestType;
  late IntersectionAccessPoint inBoundLane;
  IntersectionAccessPoint? outBoundLane = null;
  SignalRequest.fromC(C.SignalRequest c_obj) {
    id = IntersectionReferenceID.fromC(c_obj.id);
    requestID = RequestID(c_obj.requestID);
    requestType = PriorityRequestType.values[c_obj.requestType];
    inBoundLane = IntersectionAccessPoint.fromC(c_obj.inBoundLane);
    if (c_obj.outBoundLane.address != 0) {
      outBoundLane = IntersectionAccessPoint.fromC(c_obj.outBoundLane.ref);
    }
  }
}
